---
date: last-modified        # Captura la fecha real de la 칰ltima vez que guardaste el archivo
date-format: "DD/MM/YYYY"  # Define el formato espa침ol
---

# Introducci칩n {.unnumbered}

En esta unidad de **Tecnolog칤a e Ingenier칤a II**,  veremos desde los conceptos b치sicos de cargas y apoyos hasta el c치lculo de estructuras articuladas y vigas.

## Contenidos de la unidad

A continuaci칩n se detallan las secciones que componen esta unidad:

1. **Descripci칩n y elementos de estructuras sencillas**: Una visi칩n general sobre la funci칩n de las estructuras.
2. **Cargas. Tipos de apoyos y uniones**: Clasificaci칩n de las fuerzas externas a las estructuras.
3. **C치lculos b치sicos en estructuras**: Aplicaci칩n de los principios fundamentales.
4. **C치lculo de esfuerzos en vigas**: An치lisis del comportamiento de vigas sometidas a flexi칩n, axil y cortante.
5. **C치lculo de esfuerzos en estructuras de barras articuladas**: Resoluci칩n de celos칤as mediante m칠todos anal칤ticos y gr치ficos.

::: {.content-visible when-format="html"}

::: {.callout-note appearance="simple"}
## 游닄 Material de estudio
Puedes descargar esta unidad completa en formato PDF para estudiar sin conexi칩n o imprimirla:



[Descargar PDF](Unidad_7_Estructuras.pdf){.btn .btn-primary .btn-lg role="button"}
:::

:::


*칔ltima actualizaci칩n: {{< meta date >}}*
